/*
 * Type declaration for Remix build output
 * This file resolves TypeScript errors when the build directory doesn't exist
 * The actual build output is generated by running: npm run build
 */

declare module '../build/server' {
  import type { ServerBuild } from '@remix-run/cloudflare';
  const build: ServerBuild;
  export default build;
}
